-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-02-04 03:30:36 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Equipment 
    ( 
     equipment_id                     NUMBER  NOT NULL , 
     status                           NUMBER , 
     Military_Member_soldier_id       NUMBER , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Equipment_Type_equipment_type_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Equipment 
    ADD 
    CHECK (status IN (broken, functional)) 
;
CREATE UNIQUE INDEX Equipment__IDX ON Equipment 
    ( 
     Military_Member_soldier_id ASC 
    ) 
;

ALTER TABLE Equipment 
    ADD CONSTRAINT Equipment_PK PRIMARY KEY ( equipment_id ) ;

CREATE TABLE Equipment_Type 
    ( 
     equipment_type_id NUMBER  NOT NULL , 
     type              VARCHAR2 (256) 
    ) 
;

ALTER TABLE Equipment_Type 
    ADD CONSTRAINT Equipment_Type_PK PRIMARY KEY ( equipment_type_id ) ;

CREATE TABLE Location 
    ( 
     location_id NUMBER  NOT NULL , 
     country     VARCHAR2 (256) , 
     city        VARCHAR2 (256) 
    ) 
;

ALTER TABLE Location 
    ADD CONSTRAINT Location_PK PRIMARY KEY ( location_id ) ;

CREATE TABLE Military_Base 
    ( 
     base_id              NUMBER  NOT NULL , 
     name                 VARCHAR2 (256) , 
     Location_location_id NUMBER  NOT NULL , 
     type                 VARCHAR2 (18)  NOT NULL 
    ) 
;

ALTER TABLE Military_Base 
    ADD CONSTRAINT CH_INH_Military_Base 
    CHECK (type IN ('Military_Base', 'Personnel_Facility', 'Storage_Facility')) 
;


ALTER TABLE Military_Base 
    ADD CONSTRAINT Military_Base_ExDep 
    CHECK ( (type = 'Military_Base')
 OR (type = 'Personnel_Facility')
 OR (type = 'Storage_Facility')) 
;

ALTER TABLE Military_Base 
    ADD CONSTRAINT Military_Base_PK PRIMARY KEY ( base_id ) ;

-- Error - Unique Constraint Military_Base.Military_Base_PKv1 doesn't have columns -- Error - Unique Constraint Military_Base.Military_Base_PKv2 doesn't have columns

CREATE TABLE Military_Member 
    ( 
     soldier_id                 NUMBER  NOT NULL , 
     first_name                 VARCHAR2 (256) , 
     last_name                  VARCHAR2 (256) , 
     date_of_joining            DATE , 
     Rank_rank_id               NUMBER  NOT NULL , 
     Equipment_equipment_id     NUMBER , 
     Vehicle_vehicle_id         NUMBER , 
     Military_Member_soldier_id NUMBER 
    ) 
;
CREATE UNIQUE INDEX Military_Member__IDX ON Military_Member 
    ( 
     Vehicle_vehicle_id ASC 
    ) 
;
CREATE UNIQUE INDEX Military_Member__IDXv1 ON Military_Member 
    ( 
     Equipment_equipment_id ASC 
    ) 
;

ALTER TABLE Military_Member 
    ADD CONSTRAINT Military_Member_PK PRIMARY KEY ( soldier_id ) ;

CREATE TABLE Mission 
    ( 
     mission_id                 NUMBER  NOT NULL , 
     name                       VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
                    , 
     description                VARCHAR2 (256) , 
     start_date                 DATE , 
     end_date                   DATE , 
     status                     NUMBER , 
     Military_Member_soldier_id NUMBER  NOT NULL , 
     Location_location_id       NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Mission 
    ADD 
    CHECK (status IN (active, cancelled, completed, planned)) 
;

ALTER TABLE Mission 
    ADD CONSTRAINT Mission_PK PRIMARY KEY ( mission_id, Military_Member_soldier_id ) ;

CREATE TABLE Participate 
    
    -- No Columns 
    
;

CREATE TABLE Rank 
    ( 
     rank_id     NUMBER  NOT NULL , 
     name        VARCHAR2 (256) , 
     description VARCHAR2 (256) 
    ) 
;

ALTER TABLE Rank 
    ADD CONSTRAINT Rank_PK PRIMARY KEY ( rank_id ) ;

CREATE TABLE Service_Medal 
    ( 
     mission_participation_id NUMBER  NOT NULL , 
     award_date               DATE , 
     description              VARCHAR2 (256) 
    ) 
;

ALTER TABLE Service_Medal 
    ADD CONSTRAINT Service_Medal_PK PRIMARY KEY ( mission_participation_id ) ;

CREATE TABLE Service_Medal_Type 
    ( 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Service_Medal_mission_participation_id NUMBER  NOT NULL , 
     name                                   VARCHAR2 (256) 
    ) 
;

CREATE TABLE specializing 
    ( 
     Military_Member_soldier_id NUMBER  NOT NULL , 
     Specialty_specialty_id     NUMBER  NOT NULL 
    ) 
;

ALTER TABLE specializing 
    ADD CONSTRAINT specializing_PK PRIMARY KEY ( Military_Member_soldier_id, Specialty_specialty_id ) ;

CREATE TABLE Specialty 
    ( 
     specialty_id NUMBER  NOT NULL , 
     name         VARCHAR2 (256) , 
     description  VARCHAR2 (256) 
    ) 
;

ALTER TABLE Specialty 
    ADD CONSTRAINT Specialty_PK PRIMARY KEY ( specialty_id ) ;

CREATE TABLE Vehicle 
    ( 
     vehicle_id                   NUMBER  NOT NULL , 
     model_name                   VARCHAR2 (256) , 
     name                         VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
                    , 
     Military_Member_soldier_id   NUMBER , 
     Vehicle_Type_vehicle_type_id NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Vehicle__IDX ON Vehicle 
    ( 
     Military_Member_soldier_id ASC 
    ) 
;

ALTER TABLE Vehicle 
    ADD CONSTRAINT Vehicle_PK PRIMARY KEY ( vehicle_id ) ;

CREATE TABLE Vehicle_Type 
    ( 
     vehicle_type_id NUMBER  NOT NULL , 
     model_name      VARCHAR2 (256) , 
     name            VARCHAR2 (256) 
    ) 
;

ALTER TABLE Vehicle_Type 
    ADD CONSTRAINT Vehicle_Type_PK PRIMARY KEY ( vehicle_type_id ) ;

ALTER TABLE Equipment 
    ADD CONSTRAINT Equipment_Equipment_Type_FK FOREIGN KEY 
    ( 
     Equipment_Type_equipment_type_id
    ) 
    REFERENCES Equipment_Type 
    ( 
     equipment_type_id
    ) 
;

-- Error - Foreign Key Equipment_Military_Base_FK has no columns

ALTER TABLE Military_Base 
    ADD CONSTRAINT Military_Base_Location_FK FOREIGN KEY 
    ( 
     Location_location_id
    ) 
    REFERENCES Location 
    ( 
     location_id
    ) 
;

-- Error - Foreign Key Military_Member_Military_Base_FK has no columns

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Military_Member 
    ADD CONSTRAINT Military_Member_Military_Member_FK FOREIGN KEY 
    ( 
     Military_Member_soldier_id
    ) 
    REFERENCES Military_Member 
    ( 
     soldier_id
    ) 
;

-- Error - Foreign Key Military_Member_Participate_FK has no columns

ALTER TABLE Military_Member 
    ADD CONSTRAINT Military_Member_Rank_FK FOREIGN KEY 
    ( 
     Rank_rank_id
    ) 
    REFERENCES Rank 
    ( 
     rank_id
    ) 
;

ALTER TABLE Mission 
    ADD CONSTRAINT Mission_Location_FK FOREIGN KEY 
    ( 
     Location_location_id
    ) 
    REFERENCES Location 
    ( 
     location_id
    ) 
;

ALTER TABLE Mission 
    ADD CONSTRAINT Mission_Military_Member_FK FOREIGN KEY 
    ( 
     Military_Member_soldier_id
    ) 
    REFERENCES Military_Member 
    ( 
     soldier_id
    ) 
;

-- Error - Foreign Key Mission_Participate_FK has no columns

-- Error - Foreign Key Service_Medal_Participate_FK has no columns

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Service_Medal_Type 
    ADD CONSTRAINT Service_Medal_Type_Service_Medal_FK FOREIGN KEY 
    ( 
     Service_Medal_mission_participation_id
    ) 
    REFERENCES Service_Medal 
    ( 
     mission_participation_id
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE specializing 
    ADD CONSTRAINT specializing_Military_Member_FK FOREIGN KEY 
    ( 
     Military_Member_soldier_id
    ) 
    REFERENCES Military_Member 
    ( 
     soldier_id
    ) 
;

ALTER TABLE specializing 
    ADD CONSTRAINT specializing_Specialty_FK FOREIGN KEY 
    ( 
     Specialty_specialty_id
    ) 
    REFERENCES Specialty 
    ( 
     specialty_id
    ) 
;

-- Error - Foreign Key Vehicle_Military_Base_FK has no columns

ALTER TABLE Vehicle 
    ADD CONSTRAINT Vehicle_Vehicle_Type_FK FOREIGN KEY 
    ( 
     Vehicle_Type_vehicle_type_id
    ) 
    REFERENCES Vehicle_Type 
    ( 
     vehicle_type_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             4
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  15
-- WARNINGS                                 0
