-- # LOCATION
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('1', 'USA', 'New York');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('2', 'USA', 'Los Angeles');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('3', 'USA', 'Chicago');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('4', 'USA', 'Houston');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('5', 'USA', 'Phoenix');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('6', 'USA', 'Philadelphia');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('7', 'USA', 'San Antonio');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('8', 'USA', 'San Diego');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('9', 'USA', 'Dallas');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('10', 'USA', 'San Jose');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('11', 'Canada', 'Toronto');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('12', 'Canada', 'Vancouver');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('13', 'Canada', 'Montreal');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('14', 'Canada', 'Calgary');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('15', 'Canada', 'Ottawa');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('16', 'Canada', 'Edmonton');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('17', 'Mexico', 'Mexico City');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('18', 'Mexico', 'Guadalajara');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('19', 'Mexico', 'Monterrey');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('20', 'Mexico', 'Cancun');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('21', 'Argentina', 'Buenos Aires');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('22', 'Argentina', 'Cordoba');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('23', 'Argentina', 'Rosario');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('24', 'Brazil', 'Rio de Janeiro');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('25', 'Brazil', 'Sao Paulo');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('26', 'Brazil', 'Brasilia');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('27', 'Colombia', 'Bogota');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('28', 'Colombia', 'Medellin');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('29', 'Colombia', 'Cali');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('30', 'Chile', 'Santiago');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('31', 'Peru', 'Lima');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('32', 'Peru', 'Arequipa');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('33', 'Egypt', 'Cairo');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('34', 'Egypt', 'Alexandria');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('35', 'South Africa', 'Cape Town');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('36', 'South Africa', 'Johannesburg');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('37', 'South Africa', 'Durban');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('38', 'Nigeria', 'Lagos');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('39', 'Nigeria', 'Abuja');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('40', 'Kenya', 'Nairobi');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('41', 'Kenya', 'Mombasa');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('42', 'India', 'Mumbai');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('43', 'India', 'Delhi');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('44', 'India', 'Bangalore');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('45', 'India', 'Kolkata');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('46', 'Japan', 'Tokyo');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('47', 'Japan', 'Osaka');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('48', 'China', 'Beijing');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('49', 'China', 'Shanghai');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('50', 'China', 'Guangzhou');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('51', 'Australia', 'Sydney');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('52', 'Australia', 'Melbourne');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('53', 'Australia', 'Brisbane');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('54', 'New Zealand', 'Auckland');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('55', 'New Zealand', 'Wellington');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('56', 'Russia', 'Moscow');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('57', 'Russia', 'Saint Petersburg');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('58', 'Germany', 'Berlin');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('59', 'Germany', 'Munich');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('60', 'France', 'Paris');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('61', 'France', 'Marseille');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('62', 'Spain', 'Madrid');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('63', 'Spain', 'Barcelona');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('64', 'Italy', 'Rome');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('65', 'Italy', 'Milan');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('66', 'UK', 'London');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('67', 'UK', 'Manchester');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('68', 'Sweden', 'Stockholm');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('69', 'Sweden', 'Gothenburg');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('70', 'Norway', 'Oslo');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('71', 'Denmark', 'Copenhagen');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('72', 'Finland', 'Helsinki');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('73', 'Poland', 'Warsaw');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('74', 'Poland', 'Krakow');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('75', 'Ukraine', 'Kyiv');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('76', 'Ukraine', 'Lviv');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('77', 'Belarus', 'Minsk');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('78', 'Belgium', 'Brussels');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('79', 'Czech Republic', 'Prague');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('80', 'Austria', 'Vienna');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('81', 'Switzerland', 'Zurich');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('82', 'Switzerland', 'Geneva');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('83', 'Netherlands', 'Amsterdam');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('84', 'Netherlands', 'Rotterdam');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('85', 'Luxembourg', 'Luxembourg City');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('86', 'Portugal', 'Lisbon');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('87', 'Portugal', 'Porto');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('88', 'Turkey', 'Istanbul');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('89', 'Turkey', 'Ankara');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('90', 'Saudi Arabia', 'Riyadh');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('91', 'Saudi Arabia', 'Jeddah');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('92', 'United Arab Emirates', 'Dubai');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('93', 'United Arab Emirates', 'Abu Dhabi');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('94', 'Qatar', 'Doha');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('95', 'Jordan', 'Amman');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('96', 'Lebanon', 'Beirut');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('97', 'Kuwait', 'Kuwait City');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('98', 'Bahrain', 'Manama');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('99', 'Oman', 'Muscat');
INSERT INTO "LOCATION" (ID, COUNTRY, CITY) VALUES ('100', 'Egypt', 'Sharm El Sheikh');
commit;

-- # RANK
-- Enlisted
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (1, 'Private', 'Entry-level enlisted personnel');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (2, 'Private First Class', 'Junior enlisted rank above Private');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (3, 'Corporal', 'Junior non-commissioned officer');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (4, 'Specialist', 'Technical enlisted rank equivalent to Corporal');
-- Non-Commissioned Officers (NCOs)
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (5, 'Sergeant', 'First-line leader, supervises lower ranks');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (6, 'Staff Sergeant', 'Experienced NCO responsible for small units');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (7, 'Sergeant First Class', 'Senior NCO with leadership over squads/platoons');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (8, 'Master Sergeant', 'Advanced NCO with significant leadership duties');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (9, 'First Sergeant', 'Senior enlisted advisor to a company commander');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (10, 'Sergeant Major', 'Top-level NCO with leadership across battalions');
-- Commissioned Officers
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (11, 'Second Lieutenant', 'Entry-level commissioned officer');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (12, 'First Lieutenant', 'Intermediate commissioned officer');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (13, 'Captain', 'Leads a company-sized unit');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (14, 'Major', 'Field grade officer managing battalion operations');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (15, 'Lieutenant Colonel', 'Commands a battalion');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (16, 'Colonel', 'Commands a brigade or regiment');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (17, 'Brigadier General', 'Lowest general officer rank');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (18, 'Major General', 'Commands a division');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (19, 'Lieutenant General', 'Commands a corps');
INSERT INTO "RANK" (ID, NAME, DESCRIPTION) VALUES (20, 'General', 'Highest peacetime rank, commands major commands');

--